services:
  frontend:
    image: ghcr.io/carlosbrrs/beet-frontend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api-qa.tu-dominio.com
    ports:
      - "127.0.0.1:3002:3000"
    networks:
      - beet-qa-network
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: ghcr.io/carlosbrrs/beet-backend:latest
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=beet_qa
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "127.0.0.1:8082:8080"
    networks:
      - beet-qa-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=beet_qa
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data_qa:/var/lib/postgresql/data
    networks:
      - beet-qa-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  beet-qa-network:


volumes:
  db_data_qa:
